spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.trace: false 
    spring.h2.console.settings.web-allow-others: false

blog:
  path: /mnt/d/project/Blogger/blogs
  tokenLength: 10